spring:
  datasource:
    url: jdbc:h2:C:\Users\Administrator\Desktop\restaurant-api\data\restaurant-api
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test